### ISSUE TITLE
MPOS Compatibility

### ISSUE THREAD

**Issue by GQM** [z-classic/z-nomp#2] opened 2016-11-20 06:24 UTC
I believe we need to make a coin_equihash.class.php file for integrating with MPOS for things like calculating hashrate, difficulty adjustment etc.

https://github.com/MPOS/php-mpos/blob/master/include/classes/coins/coin_base.class.php#L54

**Comment by GQM** [comment] 2016-11-22 13:33
I've been trying to compare some difference between z-nomp and nomp.

When mining Litecoin I have shares submitted at

`Share accepted at diff 32/54.31050163`

VS

`Share accepted at diff 23716.080168692/0.03669559`

I believe z-nomp is tracking the network difficulty and not the set difficulty by the pool?

Looking into the database it seems that shares are being inserted at the high value 20-30k vs litecoin shares being inserted at the set stratum diff of 32.

I'm wondering if this is causing some of the issues seen in MPOS with the calculations being off.

**Comment by innova-market** [comment] 2016-11-22 17:15
I have shows 1.48 TH
![default](https://cloud.githubusercontent.com/assets/4079108/20533774/c10d4824-b0ef-11e6-97f0-4b2bec43418a.PNG)

![2](https://cloud.githubusercontent.com/assets/4079108/20533920/5cc8d12a-b0f0-11e6-8ee8-9c1096e3bb96.PNG)

**Comment by aayanl** [comment] 2016-11-22 23:32
ive been seeing this too, I would put a difficulty of 1,000, but claymore only sees it as a difficulty of 272 and mines shares like crazy.

**Comment by joshuayabut** [comment] 2016-11-23 00:45
I believe I fixed the difficulty issue. The stratum pool was using suprnova's difficulty instead of the correct proof of work difficulty. I'm looking into the payment processor issues now.

npm update && npm install to get the new code.

**Comment by joshuayabut** [comment] 2016-11-28 03:41
GQM can you try running your MPOS tests again? I've fixed the difficulty reporting.

**Comment by joshuayabut** [comment] 2016-12-02 00:12
For documentation/awareness purposes. MPOS does not intake shares with difficulties less than 1. A work around is to set the "mposDiffMultiplier" so that each share equals one but the hashrate will be skewed by that number.

**Comment by joshuayabut** [comment] 2016-12-19 04:19
I'll look over the MPOS code and submit a PR for a fix over the next week or so.

**Comment by ceozero** [comment] 2017-01-19 04:43
@GQM  can you have coin_equihash.class.php？

**Comment by GQM** [comment] 2017-01-19 05:06
Still working on a couple changes before I submit a PR to the MPOS repo.

Need an if statement that calls the config file to get the algorithm used to adjust the below line:

https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L137

Heading to the rec center for a quick swim, will try and get it done tonight when I get back.

Any suggestions on how to call/create the variable I need?

**Comment by ceozero** [comment] 2017-01-20 04:57
@GQM can you get it?

**Comment by Aleix-Oto** [comment] 2017-02-03 10:47
I am interested too..

**Comment by GQM** [comment] 2017-02-07 12:32
@ceozero @Aleix-Oto I have pushed the changes to my repo, still in development and needs to be reviewed but should be a good base. Would appreciate any feedback :)

https://github.com/GQM/php-mpos/tree/development

**Comment by EliteMobb79** [comment] 2017-02-27 04:36
@GQM Did you get payments working with MPOS compatibility? I have the z-mpos installed and working. But I found 2 blocks and payments failed to send. It seems the coinbase > private > public coin tumbling isnt happening in any capacity. I attempted to enable the payouts in z-nomp to hopefully make the coins available for the mpos to send but get errors starting the pool after enabling payout. Any luck with payouts yet? Here is the error I am getting with MPOS mode enabled and payout enabled in z-NOMP

paymentProcessor.js:172
                for (var i = 0, len = result[0].response.length; i < len; i++) {
                                                        ^

TypeError: Cannot read property 'length' of null

**Comment by aayanl** [comment] 2017-02-27 21:55
you need a script to do it https://gist.github.com/sammy007/4739e07a0ee92bde99f8f1f40835c7f1

**Comment by EliteMobb79** [comment] 2017-02-27 22:04
Excellent, thank you.

**Comment by GQM** [comment] 2017-02-28 17:18
Thanks @aayanl 

@EliteMobb79 that is the correct script which you need to run. Maybe when I find some time I can add the script into my MPOS repo for equihash. Currently driving across Canada and have little time to respond/work currently.

**Comment by EliteMobb79** [comment] 2017-02-28 17:50
No problem at all. I really appreciate the information. Safe travels.

**Comment by 6otah** [comment] 2017-03-02 12:36
@GQM can you give more detailed information on how to run this script, please? I downloaded it, inserted addresses and put it in z-nomp directory. When I run `node zdump.js` i get this:

> Balance 0 is below threshold

**Comment by sonicdx10** [comment] 2017-03-08 05:30
so autopayment for zcash is not working ?

**Comment by GQM** [comment] 2017-03-22 13:45
@6otah its a script that runs on an interval depending on whats in the settings. If there is no balance then their is nothing for the script to do. I personally use `forever` to run the script.

**Comment by aayanl** [comment] 2017-03-22 19:29
Closing as z-nomp works as intended as a backend for mpos

**Closed by aayanl** 2017-03-22 19:29 UTC
Labels: LowPriority

**Comment by vtnplus** [comment] 2017-09-24 05:21
i problem with z-nomp after update. workerName="username", last is workerName="username.worker" => error in mpos auth. where i can fix it

**Comment by OleksandrBlack** [comment] 2017-11-22 00:40
`i problem with z-nomp after update. workerName="username", last is workerName="username.worker" => error in mpos auth. where i can fix it`

**The same problem, help to solve please**
