### ISSUE TITLE
Finding first block kills the website

### ISSUE THREAD

**Issue by GRinvest** [z-classic/z-nomp#131] opened 2017-05-04 03:16 UTC
After finding the block on the Zclassic. Z-nomp stop working and get an error message:

2017-05-04 03:09:17 [Master]    [Website] Website process died, spawning replacement...
2017-05-04 05:09:21 [Website]   [Server] Website started on 0.0.0.0:80
undefined:3
var out='<style>\n    #topCharts{\n        padding: 18px;\n    }\n    #topCharts > div > div > svg{\n        display: block;\n        height: 280px;\n    }\n    .chartWrapper{\n        border: solid 1px #c7c7c7;\n        border-radius: 5px;\n        padding: 5px;\n        margin-bottom: 18px;\n    }\n    .chartLabel{\n        font-size: 1.2em;\n        text-align: center;\n        padding: 4px;\n    }\n    .chartHolder{\n\n    }\n\t\n\t#boxesLower {\n        margin: 0 9px;\n    }\n    #boxesLower > div {\n        display: flex;\n    }\n    #boxesLower > div > div {\n        flex: 1 1 auto;\n        margin: 0 9px 18px 9px;\n        padding: 10px;\n        display: flex;\n        flex-direction: column;\n    }\n    .boxLowerHeader{\n        font-size: 1.3em;\n        margin: 0 0 5px 10px;\n    }\n    #boxStatsLeft{\n        color: black;\n        background-color: #cccccc;\n    }\n    #boxStatsRight{\n\t\tcolor: black;\n        background-color: #cccccc;\n    }\n    .boxStats{\n        color: whit

TypeError: Cannot read property '00000001967d4765f0579b46feab6adf2ca59911e647d6a0d33937dd2d1c8efc' of null
    at Object.eval [as stats] (eval at doT.template (/home/z-nomp/node_modules/dot/doT.js:132:11), <anonymous>:3:6032)
    at processTemplates (/home/z-nomp/libs/website.js:61:62)
    at /home/z-nomp/libs/website.js:93:13
    at /home/z-nomp/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/z-nomp/node_modules/async/dist/async.js:998:13)
    at /home/z-nomp/node_modules/async/dist/async.js:906:16
    at /home/z-nomp/libs/website.js:86:17
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

After installation z-nomp the section Network Stats does not work. Everywhere shows 0
Any help please

**Comment by aayanl** [comment] 2017-05-04 19:50
Did you upgrade z-nomp or is this happening with a fresh install?

**Comment by hellcatz** [comment] 2017-05-04 20:13
`TypeError: Cannot read property 00000001967d4765f0579b46feab6adf2ca59911e647d6a0d33937dd2d1c8efc' of null`

Is this hash a block hash?
It may be trying to find a blockhash in an array and its missing causing the `null` exception...
I assume it is when you try to view stats.html in your browser?

**Comment by aayanl** [comment] 2017-05-04 22:51
yup http://aayanl.tech:3001/insight/block/00000001967d4765f0579b46feab6adf2ca59911e647d6a0d33937dd2d1c8efc, @GRinvest what version did you update from?

**Comment by GRinvest** [comment] 2017-05-04 23:12
This is a new installation. First I did it from here https://github.com/z-classic/z-nomp.git After I found the block This error was received. After that I installed from here https://github.com/hellcatz/z-nomp Get the same error. Pool not work After do redis-cli FLUSHALL and restart And work again. Also does not show section Network Stats Everywhere shows 0 http://zcl.minecrypto.pro/stats

**Comment by aayanl** [comment] 2017-05-04 23:13
well, `FLUSHALL` clears the redis DB completely hence the 0

**Comment by GRinvest** [comment] 2017-05-04 23:14
not show section Network Stats

**Comment by hellcatz** [comment] 2017-05-04 23:45
As a test, if you clear the contents of `stats.html` does this fix the problem?
(This will make the stats page blank on the pool of course, just trying to locate the exception...)

**Comment by GRinvest** [comment] 2017-05-04 23:56
I cleaned up the page. I'll look at the result and write

**Comment by aayanl** [comment] 2017-05-05 00:30
I'm getting the same error as well 
```
2017-05-05 00:28:59 [Pool]      [zcash_testnet] (Thread 1) Block found: 00103ecba349990d62a44ad4061fa9dc1bba643738d9fed56a8c12ea78c65f7e by tmEAUF32VncGNRKwbsyZWr1LYSwsnLZHEiA.cpu
2017-05-05 00:29:00 [Pool]      [zcash_testnet] (Thread 1) Block notification via RPC polling
undefined:3
var out='<style>\n    #topCharts{\n        padding: 18px;\n    }\n    #topCharts > div > div > svg{\n        display: block;\n        height: 280px;\n    }\n    .chartWrapper{\n        border: solid 1px #c7c7c7;\n        border-radius: 5px;\n        padding: 5px;\n        margin-bottom: 18px;\n    }\n    .chartLabel{\n        font-size: 1.2em;\n        text-align: center;\n        padding: 4px;\n    }\n    .chartHolder{\n\n    }\n\n\t#boxesLower {\n        margin: 0 9px;\n    }\n    #boxesLower > div {\n        display: flex;\n    }\n    #boxesLower > div > div {\n        flex: 1 1 auto;\n        margin: 0 9px 18px 9px;\n        padding: 10px;\n        display: flex;\n        flex-direction: column;\n    }\n    .boxLowerHeader{\n        font-size: 1.3em;\n        margin: 0 0 5px 10px;\n    }\n    #boxStatsLeft{\n        color: black;\n        background-color: #cccccc;\n    }\n    #boxStatsRight{\n\t\tcolor: black;\n        background-color: #cccccc;\n    }\n    .boxStats{\n        color: white;

TypeError: Cannot read property '00103ecba349990d62a44ad4061fa9dc1bba643738d9fed56a8c12ea78c65f7e' of null
    at Object.eval [as stats] (eval at <anonymous> (/root/git/z-nomp/node_modules/dot/doT.js:132:11), <anonymous>:3:6333)
    at processTemplates (/root/git/z-nomp/libs/website.js:61:62)
    at /root/git/z-nomp/libs/website.js:114:13
    at /root/git/z-nomp/libs/stats.js:589:13
    at /root/git/z-nomp/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/root/git/z-nomp/node_modules/async/dist/async.js:1034:13)
    at /root/git/z-nomp/node_modules/async/dist/async.js:944:16
    at Multi.callback (/root/git/z-nomp/libs/stats.js:378:21)
    at multi_callback (/root/git/z-nomp/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/root/git/z-nomp/node_modules/redis/lib/multi.js:116:9)
```

This is with the pplnt pr

**Comment by aayanl** [comment] 2017-05-05 00:38
Restarted z-nomp and founder another block and didnt crash

**Comment by aayanl** [comment] 2017-05-05 00:38
I'm guessing it only does this with the first block

**Comment by hellcatz** [comment] 2017-05-05 01:05
I believe it is something in stats.html probably do to with the confirmation lookup and the fact it's missing from the array  or the array itself doesn't exist yet...

**Comment by hellcatz** [comment] 2017-05-05 01:11
Possibly this line https://github.com/z-classic/z-nomp/blob/master/website/pages/stats.html#L161
Hince the `undefined:3`  in the report.

**Comment by hellcatz** [comment] 2017-05-05 01:42
Issue resolved with latest commit to patch-6. https://github.com/hellcatz/z-nomp/commit/8d5a13697f21e26163aa55567a00f9d54f9275b8

The problem is when the very first block is found `:blocksPendingConfirms` doesn't exist in redis; thus,
`it.stats.pools[pool].pending.confirms` doesn't exist when `stats.html` is generated.
This causes a null exception when `if (it.stats.pools[pool].pending.confirms[block[0]])`  is called.
The added `if` statement prevents the failure mode.

**Comment by GRinvest** [comment] 2017-05-05 02:04
I launched patch-6, And I'll take a look, But the demon's statistics do not show http://zcl.minecrypto.pro/stats section Network Stats. Shows 0

**Comment by GRinvest** [comment] 2017-05-05 02:22
is ok. the problem is resolved site work

**Comment by aayanl** [comment] 2017-05-05 02:27
lets keep it open till the PR is merged, that way duplicate issues dont get made

**Closed** 2017-05-11 23:05 UTC
Labels: bug

**Comment by cristiycv** [comment] 2017-08-08 08:17
May i know why i don't see the network stats on web interface? everything else is working
