### ISSUE TITLE
Duplicate Submits

### ISSUE THREAD

**Issue by dlehenky** [z-classic/z-nomp#86] opened 2017-02-14 04:59 UTC
I've been running Z-NOMP for solo mining. I've seen a number of cases where the private pool is submitting the same solution to the node for a block from 2 different miners. So, this is probably happening at the share level, as well. Anyone else notice this? It happens almost every day, and sometimes twice. I only see it at the block level, since the share data is meaningless to me, but if it's happening at the block level, it *may* be happening *much* more frequently at the share level. I'm running the master repo, not the last release.

**Comment by dlehenky** [comment] 2017-02-14 05:23
^^ I should add that I have the log files that cover examples of this, if you need them.

**Comment by aayanl** [comment] 2017-02-14 05:26
Duplicate shares only happen with low diff shares because of their low nonce range, but z-nomp should reject duplicates from miners. 2 miners submitting the block at near the same time can happen and would actually happen since miners are supposed to find that nonce.

**Comment by aayanl** [comment] 2017-02-14 05:26
I would be interested in the log though

**Comment by dlehenky** [comment] 2017-02-14 07:43
When I see the next occurrence I’ll provide you with the relevant node, Z-NOMP, and individual miner logs. Even if this is just 2 miners individually finding a solution for the same block, at the same time, one would have the “best” solution, and the pool should not report it as a “Block found” twice. Perhaps that’s just a matter of testing for that condition before the “Block found” is issued to the log. Node.js/javascript is just gooblygook to me (being an old assembler/“C” guy, myself), so I have not looked at the code.

**Comment by dlehenky** [comment] 2017-02-16 00:23
OK, got another, fresh, example. The pool log didn't show any other log entries for these 2 shares.
=======
Z-NOMP Pool Log:

2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 12) Submitted Block using submitblock successfully to daemon instance(s)
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 2) Submitted Block using submitblock successfully to daemon instance(s)
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 2) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 1) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 3) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 5) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 6) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 4) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 10) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 7) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 8) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 12) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 11) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 9) Block notification via blocknotify script
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 12) Block found: 00000006baa71a69ecefe8c00a731d1db261d687f71ab41cb760a165e403abde by node07
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 12) Share accepted at diff 32/77913.39737503 by node07 [::ffff:10.10.10.16]
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 2) Block found: 00000006baa71a69ecefe8c00a731d1db261d687f71ab41cb760a165e403abde by node09
2017-02-15 17:03:03 [Pool]  [zclassic] (Thread 2) Share accepted at diff 32/77913.39737503 by node09 [::ffff:10.10.10.19]

ZCL Node Log:

2017-02-16 00:03:03 UpdateTip: new best=00000006baa71a69ecefe8c00a731d1db261d687f71ab41cb760a165e403abde  height=58236  log2_work=43.020583  tx=149228  date=2017-02-16 00:02:24 progress=0.999991  cache=0.7MiB(745tx)
2017-02-16 00:03:03 AddToWallet e02f8c184287287cb4c76c6f143cc09f341d3914522b34f64289f6aa15e862cf  new
2017-02-16 00:03:03 keypool reserve 2
2017-02-16 00:03:03 CreateNewBlock(): total size 1000
2017-02-16 00:03:03 keypool return 2
==========

**Comment by aayanl** [comment] 2017-02-16 00:53
Thanks, I have a small idea how to resolve it, does the duplicate block show up in the redis database twice?

**Comment by dlehenky** [comment] 2017-02-16 00:58
Honestly, I don’t know. I don’t even have the Webui enabled, although redis is running (no choice). If you can tell me how to query redis from the command line, I can check it. For solo mining, I personally find little value is the pool stats, I just tail &grep the log file for “Block found”, since that’s all that matters for solo.

**Comment by aayanl** [comment] 2017-02-16 01:00
you can use redis-commander `sudo npm install -g redis-commander`, then you can just use `redis-commander` to start it

**Comment by dlehenky** [comment] 2017-02-16 01:03
Is that a GUI or cli? The rig running the zcl node and z-nomp is headless. I can only access over ssh.

**Comment by aayanl** [comment] 2017-02-16 01:04
it launches a website served over port 8081

**Comment by dlehenky** [comment] 2017-02-16 01:05
Great! Thanks!

**Comment by dlehenky** [comment] 2017-02-16 01:18
OK, so if I’m understanding what I’m looking at, the DB has only 1 share for that round, belonging to the second of the two rigs (node09).

**Comment by hellcatz** [comment] 2017-02-19 19:20
I've been looking into this issue also. You will have two pending block in "blocksPending" with the same height but different hash and only 1 of them is valid. The invalid block will show up in "getchaintips" RPC call.

I have created a "work-around" in paymentsProcessor.js to detect this invalid pending block and kick the invalid pending block to prevent payout errors. This is only sanity protection for the payment system and not a solution to the problem.
https://github.com/hellcatz/z-nomp/blob/hellcatz/libs/paymentProcessor.js#L508-L552

The issue is with node-stratum-pool. I have detected the problem here...it happens when a new block is submitted while the previous block is still being processed by the daemon. The new block is processed at the same block height. Read my commit notes...
https://github.com/hellcatz/node-stratum-pool/commit/4f60132e3be23c71b9ef021034a0f0b4956954c3

I'm still testing on the zcash testnet (not zclassic).  I have a couple ideas to possibly solve the issue, I have not been able to test them yet...

**Comment by wariner84** [comment] 2017-03-09 06:58
Hi,
I have same problem, you have found a solution?

**Comment by ziomik** [comment] 2017-03-09 07:11
Database redis blocksPending (2) with two different codes for the same block, it is now in pending (we surpassed 100 confirmations) but remains pending! Solution? Thanks

https://i.gyazo.com/1bc6a3a86d3cb228c98953ace2964e56.png

**Comment by aayanl** [comment] 2017-03-12 16:44
should be fixed with 86778a2ae27cb327e9db468627891c37a94bcc30

**Comment by hellcatz** [comment] 2017-04-02 00:21
It is with my latest "major update 2" pull request.
Tested and proven to fix payments glitches from invalid duplicate blocks on zcash_testnet.
Invalid duplicate blocks are moved to "blocksDuplicate" in redis before causing payment issues.
Unfortunately, these blocks are truly invalid and must be marked as duplicates.

See Screenshow Below:
![image](https://cloud.githubusercontent.com/assets/22487711/24583455/58c01960-16ff-11e7-950f-ac283be99068.png)

**Comment by aayanl** [comment] 2017-04-10 02:59
Should be fixed now with v1.0.3 I hope

**Closed by aayanl** 2017-04-10 02:59 UTC
