### ISSUE TITLE
99% CPU Usage from zcashd.

### ISSUE THREAD

**Issue by Xandrah** [z-classic/z-nomp#130] opened 2017-05-02 18:38 UTC
I have been using z-nomp for a while and love the software, but after mining the last block I have encountered issues with z-nomp, it will cause the zcashd process to constantly run at 100% CPU causing the daemon to become unresponsive.

**Comment by ghostnegotiator** [comment] 2017-05-02 18:42
That might be caused by zcashd has allot of transactions to process and got out of sync. When you check your Z-NOMP logs you should be able to see it is unresponsive due ??? reason. When the wallet is syncing or is slacking behind it will take up allot of resources just to catch up.

This can be simply fixed by restarting the wallet so it verifies the chain and should be good to go again. When this happen allot more consider getting more RAM in the Machine or VPS.

**Comment by Xandrah** [comment] 2017-05-02 18:52
The machine has 48GB ram so its not a memory issue, but after disabling shielding and restarting z-nomp zcashd process went back to around 2% CPU usage.

**Comment by aayanl** [comment] 2017-05-02 21:57
Try making blockRefreshInterval higher https://github.com/z-classic/z-nomp/blob/master/config_example.json#L13

**Comment by aayanl** [comment] 2017-05-02 22:07
also try using blocknotify https://github.com/z-classic/z-nomp#optional-recommended-setting-up-blocknotify

**Comment by Xandrah** [comment] 2017-05-02 22:18
Thanks for the response, I have setup blocknotify, still z-nomp sends a rpc request for it too, which is stange. How do I make it only use blocknotify script?

**Comment by dlehenky** [comment] 2017-05-02 22:53
If you use “blocknotify” you have to set “blockRefreshInterval” to 0 to disable RPC polling.

**Comment by Xandrah** [comment] 2017-05-03 08:34
Sadly zcashd is still spitting out tons of those errors.

**Comment by aayanl** [comment] 2017-05-04 20:11
Possible reliever with #132, the main issue is with zcash though

**Closed** 2017-05-11 23:06 UTC
Labels: bug, HighPriority
